### ISSUE TITLE
No updates?

### ISSUE THREAD

**Issue by esvirskiy** [Twingate/helm-charts#10]
Are helm charts no longer being updated with the latest versions?

**Comment by yafanasiev** [comment]
@esvirskiy AFAIK the chart uses "twingate/connector:1" image which always points to the latest image with major "1". So to update the connector to the latest version you need to re-create pods so new image will be pulled due to `pullPolicy: Always`. Although I don't like this behaviour and would prefer better release cycle - almost all Helm project bump app version alongside the chart version to ensure consistent deployments. If maintainers are open for this discussion I could help with setting this up alongside some minor improvements to the chart itself.

**Comment by ekampf** [comment]
Hey @esvirskiy and @yafanasiev.
Yes, we do, by default deploy `connector:1` so you automatically get all the minor versions versions and we don't have to update the chart with each release.
You can change that behavior by setting a more specific tag on `values.yaml` - https://github.com/Twingate/helm-charts/blob/master/stable/connector/values.yaml#L7

The thinking behind this is that we (Twingate) ensure compatibility of all minor versions so its not something you really have to care about...
But, we're open to discussion and you can feel free to drop me a message at eran@twingate.com and we can discuss it.
